[package]
name = "wordlist_gen"
version = "0.1.0"
authors = ["Daniel R Gulotta <dgulotta@alum.mit.edu>"]
edition = "2018"

[dependencies]
csv = "^1.0"
clap = "^2.31"
curl = "^0.4"
flate2 = "^1.0"
rayon = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
unidecode = "^0.3"
